#ifndef BJN_ERROR_H
#define BJN_ERROR_H
#include "iostream"
const std::string BJN_EMPTY_STR = "";

namespace bjn_sky {

//When adding extra error codes in this enum also add equivalient string in array errorStr in file error.cpp
//Also update the wiki page at https://sites.google.com/a/bluejeansnet.com/eng/docs/skinny-architecture/skinny-error-codes
enum errorCode {
    ERROR_NONE,
    ERROR_DEV_UNAVAILABLE,
    ERROR_MEDIA_STREAM_NULL,
    ERROR_WINDOW_NOT_CREATED,
    ERROR_SIGNAL_CHANNEL_NOT_CREATED,
    ERROR_LOGIN_FAIL,
    ERROR_INVALID_DEVICES,
    ERROR_GET_USER_MEDIA,
    ERROR_INVALID_USERNAME,
    ERROR_REMOTE_STREAM_NOT_CREATED,
    ERROR_ALREADY_LOGGEDIN,
    ERROR_INCORRECT_DATE_STRING_PATTERN,
    ERROR_INVALID_URL,
    ERROR_NO_LOGFILE_FOR_SEARCH_CRITERIA,
    ERROR_LOGFILE_NOT_FOUND,
    ERROR_DOWNLOAD_FAILED,
    ERROR_INSTALLATION_FAILED,
    ERROR_INIT_MEDIA_FAILED,
    ERROR_INIT_PRESENCE_FAILED,
    ERROR_PRESENTATION_REQ_FAILED,
    ERROR_CALL_FAIL,
    ERROR_MIC_ENHANCEMENTS_SET_FAILED,
    ERROR_SPK_ENHANCEMENTS_SET_FAILED,
    ERROR_SPK_FAILED,
    ERROR_XP_VERSION_NOT_SUPPORTED,
    ERROR_MICROPHONE_NOT_WORKING,
    ERROR_SPEAKER_NOT_WORKING,
    ERROR_NO_CA_CERTIFICATE,
    ERROR_UPLOAD_IN_PROGRESS,
    ERROR_UPLOAD_FAILED,
    ERROR_UPLOAD_CANCELED,
    ERROR_WARN_RTCP_TIMEOUT,
    ERROR_LINUX_AUTO_UPDATE_NOT_SUPPORTED,
    ERROR_MEETING_RUNNING,
    ERROR_WARN_MEETING_RECONNECT,
    ERROR_WARN_DUAL_STREAM_DISABLED,
    ERROR_WARN_MACAIR6_NO_CAM,
    ERROR_SIGNAL_CHANNEL_ALREADY_CREATED,
    ERROR_CAMERA_DEVICE_BUSY,
    ERROR_MAX_CODE, //Don't add error codes after this
};

extern std::string errorStr[ERROR_MAX_CODE + 1] ;

}
#endif // BJN_ERROR_H

